export * from './header/Header'
export * from './welcome/Welcome'
export * from './about/About'
export * from './social/Social'
export * from './work/Work'
export * from './work-two/WorkTwo'
export * from './basic-tabs/BasicTabs'
export * from './contact/Contact'